# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/qt_ui/main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_screen(object):
    def setupUi(self, screen):
        screen.setObjectName("screen")
        screen.resize(804, 619)
        self.central = QtWidgets.QWidget(screen)
        self.central.setObjectName("central")
        self.tabWidget = QtWidgets.QTabWidget(self.central)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.tabWidget.setObjectName("tabWidget")
        screen.setCentralWidget(self.central)
        self.menubar = QtWidgets.QMenuBar(screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 22))
        self.menubar.setObjectName("menubar")
        screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(screen)
        self.statusbar.setObjectName("statusbar")
        screen.setStatusBar(self.statusbar)

        self.retranslateUi(screen)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(screen)

    def retranslateUi(self, screen):
        _translate = QtCore.QCoreApplication.translate
        screen.setWindowTitle(_translate("screen", "MainWindow"))
